# Generated by Django 4.1.1 on 2022-09-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_technology_project_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='alt_text',
        ),
    ]
