# Generated by Django 4.1.1 on 2022-09-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
