# Generated by Django 4.1.1 on 2022-09-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_project_technologies_delete_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='added',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
